{% set name = "bofire" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bofire-{{ version }}.tar.gz
  sha256: 6272e01203da28423dbdd679b5e3e86a65bcca911f09245066e39f6eafa35c0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - formulaic ==1.0.1
    - typing_extensions
    - python >={{ python_min }}
    - numpy
    - pandas
    - pydantic >=2.5
    - scipy >=1.7
    - typing-extensions

test:
  imports:
    - bofire
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Experimental design and (multi-objective) bayesian optimization.
  home: https://github.com/experimental-design/bofire
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
