{% set name = "bofire" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bofire-{{ version }}.tar.gz
  sha256: 4bffe990d6701b86bb71d9f04e2e253bd72fd48b7b80b6ab54693b169e730e20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - typing_extensions
    - python >={{ python_min }}
    - numpy
    - pandas
    - pydantic >=2.5
    - scipy >=1.7,<1.15
    - typing-extensions

test:
  imports:
    - bofire
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Experimental design and (multi-objective) bayesian optimization.
  home: https://github.com/experimental-design/bofire
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
